spring:
  application:
    name: cheplay

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4jpassword

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.neo4j: INFO
    com.cheplay: DEBUG
